### ISSUE TITLE
Openness to move from curl to reqwest?

### ISSUE THREAD

**Issue by sseemayer** [xd009642/coveralls-api#9]
Thanks for this project, and a huge thanks for tarpaulin!

I am in a corporate environment where CI builds are currently failing due to issues downloading the `curl` source code as part of the `curl-sys` crate (a dependency of the `curl` crate used by `coveralls-api`) while trying to `cargo install cargo-tarpaulin`. It looks like some firewall that is between our CI servers and the cargo registry is aborting the HTTP connection partially through the download of the curl source tarball.

While we are still troubleshooting the download issue, I was wondering if you would be open in principle to changing the crate used for performing HTTP requests from `curl` to `reqwest`? As far as I can tell, that crate, while slightly larger than curl, does not need to pull in non-rust libraries and compile them from source, and is the more widely used HTTP client library in Rust.

If you are open to this suggestion, I would be happy to take a stab at a PR.

**Comment by xd009642** [comment]
So I'm open to this if you can get it working, I did initially start with hyper in 2017 but there was something weird in the coveralls API that just meant I couldn't get it working as easily so I switched to curl in the interest of something working. I can't remember what was wrong though and my commit messages from then were very _sparse_.

**Comment by xd009642** [comment]
So now this is merged I'm going to push out a coveralls release. Then you should be able to use it at work by installing from the git develop branch once  https://github.com/xd009642/tarpaulin/pull/1399 merges
